# Generated by Django 4.2.4 on 2023-10-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Клиент')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание клиента')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail ')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('last_modified_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mailing', models.DateTimeField(verbose_name='Дата рассылки')),
                ('succes_mail', models.BooleanField(default=False, verbose_name='Успешная отправка')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ('time_mailing',),
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_email', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('body_email', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения для рассылки ',
                'ordering': ('subject_email',),
            },
        ),
        migrations.CreateModel(
            name='mailingsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(verbose_name='время рассылки')),
                ('start_of_mailing', models.DateTimeField(verbose_name='Дата начала рассылки')),
                ('Mailing_schedule', models.CharField(choices=[('day', 'Ежедневно'), ('week', 'Еженедельно'), ('month', 'Ежемесячно')], default='day', max_length=5, verbose_name='График рассылки')),
                ('status', models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена')], default='day', max_length=10, verbose_name='Статус рассылки')),
                ('client', models.ManyToManyField(limit_choices_to={'owner': True}, to='sendyoumail.client')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('start_of_mailing',),
            },
        ),
    ]
